### ISSUE TITLE
This extension appears to work with Gnome 3.18 on the Extensions website

### ISSUE THREAD

**Issue by ElectricPrism** [rastersoft/slingshot_app_launcher#6]
On this page
https://extensions.gnome.org/extension/578/slingshot-app-launcher/

On both Firefox and Ephiphany I can enable the extension on my Gnome 3.18 Archbox. Obviously this is either a bug associated with the extensions website or this plugin, perhaps the checker notices 3.8 support in the metadata.json and confuses it with 3.18 and thinks it's supported.

Although I do admit I was excited at the notion of the 3.18 version, this is definately some kind of bug.

**Comment by rastersoft** [comment]
Hi:

I applied the bugfix that should allow to use it with gnome shell 3.12 and 3.14; unfortunately it seems incompatible with 3.18. Anyway, this extension is obsolete, and now I recommend to use Panther Launcher, which allows to use a slightly modified version of the original Slingshot Launcher with Gnome Shell. You can find its code here, in my github account, and also packages for debian, ubuntu, fedora and arch in my homepage (http://www.rastersoft.com).
