### ISSUE TITLE
Installation fails on PurOS

### ISSUE THREAD

**Issue by derrelldurrett** [rastersoft/slingshot_app_launcher#7]
It's entirely possible I have done something wrong, or failed to do everything necessary to install your app launcher. I have a new PurOS machine, and am trying to make it more user-friendly. I was trying to install your application from gnome-tweaks. It shows a failure from attempting to install it. And when I launch the "settings" icon from gnome-tweaks, I see the attached dialog.

![slingshot-app-launcher-fail](https://user-images.githubusercontent.com/2601451/62402253-14084280-b544-11e9-9111-513524b3b8d9.png)

Please let me know what additional information I can provide.

**Comment by rastersoft** [comment]
Last time I updated slingshot app launcher was five years ago, for Gnome Shell 3.12... Currently I don't maintain it. What I use (and created) is Activity App Launcher https://gitlab.com/rastersoft/activityAppLauncher
